name: kirkuc_numara
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.12.0
  firebase_auth: ^3.3.7
  cloud_firestore: ^3.1.8
  firebase_storage: ^10.2.7
  mobx: ^2.0.6+1
  flutter_mobx: ^2.0.4
  flutter_screenutil: ^5.2.0
  cupertino_icons: ^1.0.2
  auto_size_text: ^3.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.5+2  
  build_runner: ^2.1.7
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


